Repository ZohrehGit/Group7-EasyShop-Website, pull requests merged in 2024-04, with the labels that each got.

#9 ZS- sign up functionality done
  Sign up functioality
Labels: Tasks

#13 Update README.md -1
  README.md
Labels: enhancement

#20 AB#11 Features by Georgii + README added info
  README.md
  shopping_cart.html
Labels: Tasks

#29 AB#19 customers
  db/customers.sql
Labels: enhancement, Tasks

#12 Sign in functioality start
  Sign in functioality
Labels: Tasks

#32 Release 1.2 beta
  Create account
  shopping_cart.html
  styles.css
Labels: enhancement
